#!/bin/bash

IMAGES_DIRECTORY="/trainingData"
EXAMS_METADATA_FILENAME="/metadata/exams_metadata.tsv"
IMAGES_CROSSWALK_FILENAME="/metadata/images_crosswalk.tsv"
PREPROCESS_DIRECTORY="/preprocessedData" 
IMAGE_LABELS_FILENAME="$PREPROCESS_DIRECTORY/metadata/image_labels.txt"

PREPROCESS_IMAGES_DIRECTORY="$PREPROCESS_DIRECTORY/images" 
PREPROCESS_IMAGES_TRAIN_DIRECTORY="$PREPROCESS_IMAGES_DIRECTORY/train"
PREPROCESS_IMAGES_VAL_DIRECTORY="$PREPROCESS_IMAGES_DIRECTORY/val"
PREPROCESS_IMAGES_TRAIN_CLASS0_DIRECTORY="$PREPROCESS_IMAGES_TRAIN_DIRECTORY/0"
PREPROCESS_IMAGES_TRAIN_CLASS1_DIRECTORY="$PREPROCESS_IMAGES_TRAIN_DIRECTORY/1"
PREPROCESS_IMAGES_VAL_CLASS0_DIRECTORY="$PREPROCESS_IMAGES_VAL_DIRECTORY/0"
PREPROCESS_IMAGES_VAL_CLASS1_DIRECTORY="$PREPROCESS_IMAGES_VAL_DIRECTORY/1"


python training.py $PREPROCESS_IMAGES_TRAIN_DIRECTORY $PREPROCESS_IMAGES_VAL_DIRECTORY $PREPROCESS_IMAGES_TRAIN_CLASS0_DIRECTORY $PREPROCESS_IMAGES_TRAIN_CLASS1_DIRECTORY $PREPROCESS_IMAGES_VAL_CLASS0_DIRECTORY $PREPROCESS_IMAGES_VAL_CLASS1_DIRECTORY

echo "Done subfoldering!"
