#!/bin/bash

IMAGES_DIRECTORY="/trainingData"
EXAMS_METADATA_FILENAME="/metadata/exams_metadata.tsv"
IMAGES_CROSSWALK_FILENAME="/metadata/images_crosswalk.tsv"
PREPROCESS_DIRECTORY="/preprocessedData"
WRITEABLE_METADATA_DIRECTORY="/$PREPROCESS_DIRECTORY/metadata"
IMAGE_LABELS_FILENAME="$PREPROCESS_DIRECTORY/metadata/image_labels.txt" #2

PREPROCESS_IMAGES_DIRECTORY="$PREPROCESS_DIRECTORY/images" 
PREPROCESS_IMAGES_TRAIN_DIRECTORY="$PREPROCESS_IMAGES_DIRECTORY/train"
PREPROCESS_IMAGES_VAL_DIRECTORY="$PREPROCESS_IMAGES_DIRECTORY/val"
PREPROCESS_IMAGES_TRAIN_CLASS0_DIRECTORY="$PREPROCESS_IMAGES_TRAIN_DIRECTORY/0"
PREPROCESS_IMAGES_TRAIN_CLASS1_DIRECTORY="$PREPROCESS_IMAGES_TRAIN_DIRECTORY/1"
PREPROCESS_IMAGES_VAL_CLASS0_DIRECTORY="$PREPROCESS_IMAGES_VAL_DIRECTORY/0"
PREPROCESS_IMAGES_VAL_CLASS1_DIRECTORY="$PREPROCESS_IMAGES_VAL_DIRECTORY/1"

MODEL_STATE_DIRECTORY="/modelState"

python training.py $PREPROCESS_IMAGES_DIRECTORY $IMAGE_LABELS_FILENAME $PREPROCESS_IMAGES_TRAIN_CLASS0_DIRECTORY $PREPROCESS_IMAGES_TRAIN_CLASS1_DIRECTORY $PREPROCESS_IMAGES_VAL_CLASS0_DIRECTORY $PREPROCESS_IMAGES_VAL_CLASS1_DIRECTORY $EXAMS_METADATA_FILENAME $IMAGE_CROSSWALK_FILENAME

echo "Done training!"
